apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delta-station-outputs
  namespace: delta-station
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path   # k3sデフォルト
  resources:
    requests:
      storage: 20Gi
